### PR TITLE
V3.15.3

### PR DESCRIPTION
**Pull request by mark0n**
I felt like it's time to finally have packages for 3.15 ;-) Note that I ported all patches from 3.14.12.3 except for [one which adds a new feature and thus should be submitted upstream instead](https://github.com/epicsdeb/epics-base/blob/master/debian/patches/0028-Report-ACF-file-hash-over-CA.patch). The package builds fine on Jessie and Wheezy.

### CODE REVIEW

**Comment by ralphlange** [comment]
The 3.14 branch is still supported.

Do we need a new set of packages for 3.14, and two master branches in the epicsdeb repo?
Or do we decide to end the packaged release series of 3.14 at this moment?

**Comment by ralphlange** [comment]
Please add the patch to fix the Launchpad bug [#1466129](https://bugs.launchpad.net/epics-base/+bug/1466129) that is available on the [known problems page](http://www.aps.anl.gov/epics/base/R3-15/3-docs/KnownProblems.html).
These changes will become part of 3.15, and they have been tested for Linux (which is our target here).

**Comment by mark0n** [comment]
Thanks for pointing me to the patch mentioned on the known bugs page. This one should certainly be in our package so I added it.

Regarding the v3.14 branch: I would prefer to merge the changes for 3.15 to master and create a new branch master3.14 for further development on 3.14. Note however that I am not planning to support 3.15 myself since this version will not be used at FRIB.

**Comment by mdavidsaver** [comment]
How was the upstream branch updated?  Was this directly from http://www.aps.anl.gov/epics/download/base/base-3.15.3.tar.gz or were modifications made?

**Comment by mark0n** [comment]
Essentially I ran:
```
wget -O epics-base_3.15.3.orig.tar.gz http://www.aps.anl.gov/epics/download/base/base-3.15.3.tar.gz
gbp-clone git@github.com:epicsdeb/epics-base.git
cd epics-base/
git checkout -b v3.15.3
gbp-pq import
git-import-orig -u3.15.3 --pristine-tar --debian-branch=v3.15.3 ../epics-base_3.15.3.orig.tar.gz
gbp-pq rebase
```
So, I guess the answer is: No modifications.

**Comment by mdavidsaver** [comment]
I think this is all ok, but I'm going to hold off on merging until I've looked through #5.

**Comment by mdavidsaver** [comment]
> E: epics-perl: missing-dependency-on-perlapi
> E: epics-dev: pkg-config-bad-directive usr/share/pkgconfig/epics-base-linux-x86_64-debug.pc -D_FORTIFY_SOURCE=2
> E: epics-dev: pkg-config-bad-directive usr/share/pkgconfig/epics-base-linux-x86_64.pc -D_FORTIFY_SOURCE=2
> E: epics-doc: privacy-breach-w3c-valid-html usr/lib/epics/html/CAref.html (http://www.w3.org/icons/valid-html401)

FYI I do see 4 lintian errors.  The middle two I understand, the filters in src/tools/Makefile should I guess be extended remove "-D_FORTIFY_SOURCE%".

**Comment by mdavidsaver** [comment]
'-fno-strict-aliasing' should also be filtered out.  It seems to be sneaking into the pkgconfig for RTEMS-mvme5500.

**Comment by mdavidsaver** [comment]
For future reference, hashes of the orig tar (md5, sha1, sha256) which I'm adding to the pristine-tar branch.

> d2c32714a83cf72f07b180d1fca2b82e  epics-base_3.15.3.orig.tar.gz
> ca120492e63c25fd2cbf1f389faf4971196e2457  epics-base_3.15.3.orig.tar.gz
> 76c6d6e487a7c6a1b1b72ce7a7f4a3e2dd6a4617b789c00adf479b96dcc7055e  epics-base_3.15.3.orig.tar.gz

**Pull request merged**
