### PR TITLE
Apply MMIO VxWorks patch

### PR DESCRIPTION
**Pull request by mark0n**

### CODE REVIEW

**Comment by mdavidsaver** [comment]
Why do we need a vxWorks specific patch?

**Comment by mark0n** [comment]
Users might want to cross-build for VxWorks...

**Comment by mdavidsaver** [comment]
"might"?  I know of no one doing this in the context of debian packaging.  In fact, to my (second hand) knowledge, packaging vxWorks itself would be against it's licensing.  The patch stack for this package gets large enough as it is.  My inclination is not to backport target/OS specific patches except for linux, rtems, and windows/mingw.

**Comment by mark0n** [comment]
Sounds reasonable. Closed until someone asks for it.

**Pull request closed without merging**
