### PR TITLE
V3.15.6

### PR DESCRIPTION
**Pull request by mark0n**
Note: This still needs more testing. I'm planning to deploy to the IOCs on our test network as soon as I got the most important modules to build on stretch.

### CODE REVIEW

**Comment by mark0n** [comment]
We tested this on our test network - seems to work fine.

**Comment by aderbenev** [comment]
I jumped on that to deal with backlog of Debian things, only to remember that all dependent packages now need to be rebuilt. This one builds without issues by itself though... PRs for sscan, autosave, seq will be parts of that endeavor I guess.

**Comment by mark0n** [comment]
Updating other packages shouldn't be necessary - if they built against 3.15.3 they should also build against 3.15.6. With that in mind is there anything that needs to be done before we can merge this? We have successfully deployed this to a bunch of production machines already :-)

P.S.: I recently applied a patch for a regression in MSI.

**Comment by mark0n** [comment]
At FRIB I'm deploying a version that also has a patch adding my callback queue status feature (which is already part of 3.16.2). If you are interested I can push that as well.

**Comment by aderbenev** [comment]
I have someone crunching through all major packages and PRs, results going in our Debian 9 staging mirror: https://epicsdeb.bnl.gov/debian/stretch.html. It's a bit of a learning curve...

As it was planned, 32 bit was dropped for this endeavor and so was RTEMS (that we tried but things became too cryptic). There are few hiccups, but most things went straightforwardly after that.

We're getting to testing and closing PRs soon-ish...

**Comment by aderbenev** [comment]
3.15.6-2 available in NSLS-II Debian repo [here](https://epicsdeb.bnl.gov/debian/pool/main/e/epics-base/). Rest of staging should be built on this currently, and we're running that for dev environment for some time. New stretch systems have that installed - no issues reported thus far.

**Pull request merged**
